### ISSUE TITLE
"Please enter wallet password" request not needed?

### ISSUE THREAD

**Issue by xtc0r** [lukso-network/tools-lukso-cli#197]
When I start my validator I'm asked:

`Please enter your wallet password:`

The code for this seems to come from [here](https://github.com/lukso-network/tools-lukso-cli/blob/7972a4a3a3a9ad1f07d06962adf7cd99e464864b/common/utils/files.go#L138)

What is this used for? The validator keys are stored in the corresponding file under `/validators`

**Comment by richtera** [comment]
Yes it reads the password into memory to be able to pipe it to the actual client. The client (like prysm) itself needs to run as a non-interactive daemon so that it does not affect or connect to the current tty.

**Comment by xtc0r** [comment]
Your 'yes' refers to my question that it's not needed or something else?
So I'm using lighthouse and I don't know why I'm asked to enter a wallet password.

**Comment by richtera** [comment]
It is needed to get the password for the wallet unless you're providing the password within a file and pointing to it. I.e. the validator needs to read it on startup

**Comment by richtera** [comment]
Oh I see you're being asked for the password earlier than required. I will check.

**Comment by xtc0r** [comment]
I imported my validators pointing to a pw file. Lighthouse stores the password for each validator in a file. When the import is done there is no need to ask lighthouse users for any password as the password is used from the file lighthouse generated during the validator import.
I can't check the file name right now. But it is in the validator folder.

**Comment by richtera** [comment]
I see the password file sent to lighthouse is the file that this pipe is supposed to represent. So it looks like for lighthouse it might not be sensing that you' are specifying the password from a file to disable the prompt. Makes sense. Sounds like we need some adjustment.

**Comment by xtc0r** [comment]
[Here](https://lighthouse-book.sigmaprime.io/mainnet-validator.html#:~:text=The%20user%20can%20choose%20whether%20or%20not%20they%27d%20like%20to%20store%20the%20validator%20password%20in%20the%20validator_definitions.yml) you find the official documentation of lighthouse about the validator password storage. They store the name and password of each validator in the [validators_definition.yml ](https://lighthouse-book.sigmaprime.io/validator-management.html#:~:text=Introducing%20the%20validator_definitions.yml%20file). 
So the prompt should only appear when there is a validator in the `validator_definitions.yml` where the password field is empty. Otherwise skip the password prompt because every validator has a password set in the `validator_definitions.yml`.
The prompt blocks automated restarts of the service.

**Comment by richtera** [comment]
As a workaround you can provide the password file option pointing to a dummy file.
So if you defined --validator-wallet-password to point to a file it will not prompt and send that file which should then be ignored. That might be a workaround until we repair this.
