### ISSUE TITLE
Downloading Nethermind for arm -> wrong DL link

### ISSUE THREAD

**Issue by xtc0r** [lukso-network/tools-lukso-cli#264]
Installing Nethermind on arm via Lukso CLI fails.

`INFO[0016] :arrow_down:  Downloading Nethermind...                
WARN[0016] :warning:  File under URL https://github.com/NethermindEth/nethermind/releases/download/1.27.0/nethermind-1.27.0-220b5b85-linux-aarch64.zip not found - skipping... 
ERRO[0016] :x:  There was an error while downloading Nethermind: chmod clients/nethermind: no such file or directory `

Correct link is:
`https://github.com/NethermindEth/nethermind/releases/download/1.27.0/nethermind-1.27.0-220b5b85-linux-arm64.zip`

**Comment by Wolmin** [comment]
This should be fixed in [v0.23.1](https://github.com/lukso-network/tools-lukso-cli/releases/tag/v0.23.1) release. Please let us know if there are any further issues with this install.
