### ISSUE TITLE
GLIBC 2.32/34

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/tools-lukso-cli#88]
## Type

Bug

## Description

When executing `lukso init` it requires glibc 2.32 minimum. I am running 20.x LTS ubuntu. Unless there is a hard requirement for glibc 2.32 and above, I would like to ask to target 2.31 or below to have a wide support of OS versions.

```
lukso@lukso:~/node$ lsb_release -d
Description:	Ubuntu 20.04.6 LTS
```

```
lukso@lukso:~/node$ lukso init
lukso: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by lukso)
lukso: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by lukso)
lukso@lukso:~/node$ glib-compile-schemas ^C
lukso@lukso:~/node$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

## Resources

* `GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main main.go` etc.
* Ubuntu 22.04.2 LTS works/supported. User can upgrade they system to 22.04

**Comment by fhildeb** [comment]
Thanks, Vlad for pointing it out 👍🏻 Much appreciated

**Comment by Hugoo** [comment]
Hi @lykhonis thanks for the issue.

How did you install the CLI? Build from source?
The current version available through the install script is quite outdated. ~~I managed to run the CLI on ubuntu 22~~ -> i didnt test on ubuntu 20.

**Comment by lykhonis** [comment]
> Hi @lykhonis thanks for the issue.
> 
> How did you install the CLI? Build from source? The current version available through the install script is quite outdated. I managed to run the CLI on ubuntu 22

I tried to use install script (it works). `lukso init` (actual execution) results in missing dependency. Then I proceeded to `do-release-upgrade` which brought my ubuntu to 22.04 LTS. At this point, CLI works fine.
